name: Hello

on: [push]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo Command
        run: |
          echo "Hello World"
          echo "Welcome to GitHub"

